### ISSUE TITLE
code is not valid :(

### ISSUE THREAD

**Issue by mantas-done** [Apress/domain-driven-laravel#2]
https://github.com/Apress/domain-driven-laravel/blob/1c7f1c8f59275fb0fe8ec8d209a3521ebbe22ac5/Chs1and2/1_1.php#L8

**Comment by snipertomcat** [comment]
How do you figure that the code isn't valid? Its a standard class-member assignment variable named $table, which equals 'customers' and is scoped to `public`. I don't see any issue here

**Comment by desplega** [comment]
It seems all the quotes in the php files are wrong. They need to be converted to valid ones:

public $table = ‘customers’;    ----->    public $table = 'customers';

**Comment by snipertomcat** [comment]
That was actually not my doing. The source code in the book has all the correct quotes replaced with backticks. Im guessing that's how the publisher does it (although I'm not sure as to why). I am building out the code for the book now, which will not have any such errors. Stay tuned
